meta_title: "medGo - Le remplacement médical à portée de main"
meta_description: "Trouvez votre remplacement ou remplaçant en quelques clics. Médecins, dentistes, kinés et toute autre profession médicale."
meta_image: "Logo_Facebook.png"
# twitter_account: "@AntoineLoron" # indispensable pour les Twitter Cards
