meta_title: "medGo - Levez le pied, vous êtes remplacés"
meta_description: "Le réseau des professions médicales. Trouvez votre remplacement ou remplaçant en quelques clics. Médecins, dentistes, kinés et toute autre profession médicale."
meta_image: "Logo_FB.png"
# twitter_account: "@AntoineLoron" # indispensable pour les Twitter Cards
